version: '3'

services:
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/database/data:/var/lib/mysql
    ports:
      - "13306:3306"

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        UID: ${UID:-1000}  # Используем UID пользователя хоста
        GID: ${GID:-1000}  # Используем GID пользователя хоста
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=8.0
    volumes:
      - ./:/var/www/
      - ./docker/php-fpm/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/
      - /var/www/docker/ #ignore docker dir
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "4080:80"
      - "4443:443"
